# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f47122b03ad61d5b245122774d4f63c6281cd0fda56ae6a75f6a3ffcc1e1de7eceb5e3b67b75829d467168fb2d384d08ed42912c7d8bc267e8cf2e83cc3ad561

test:
  secret_key_base: f3539a1d00f1f7af447e210977625bb00bd586f45ca6c5ef8567903c64776be0cf7168abcde2d7f21cb6e895cceecb0e2567ecb6d36d7bea7eb6cd60c0ce1f1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
